### ISSUE TITLE
tile is not shown completely

### ISSUE THREAD

**Issue by Haikuch** [mapswipe/mapswipe.github.io#3] opened 2017-03-26 00:49 UTC
on my (elderly) Lenovo Tab 5500h (8 inch) I have problems with the top and bottom border of the tiles. There is always missing some pixels, so there is a offset between two tiles. Its ok from right to left, but not from top to bottom. When I "zoom" the tile, I can see the whole one.

![eins](https://cloud.githubusercontent.com/assets/9150258/24327333/65367970-11c6-11e7-8f08-9a88aa8f8809.png)
![zwei](https://cloud.githubusercontent.com/assets/9150258/24327332/5b67e9b0-11c6-11e7-9a64-5fb608f215ef.jpg)

**Comment by mathcass** [comment] 2017-07-21 11:23
Thank you for the feedback @Haikuch on this. I believe I've confirmed this on my own devices.

**Comment by tastrax** [comment] 2017-10-07 04:44
The same issue also occurs on iPad Air 2. There is continually a white bar at the top of the screen that is never used in the app. All tiles are rectangular until pressed and only then do you see the full square tile.

**Comment by Hagellach37** [comment] 2019-07-23 10:09
closing this issue, since it is already described in https://github.com/mapswipe/mapswipe/issues/33

**Closed by Hagellach37** 2019-07-23 10:09 UTC
